ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;


select username from dba_users order by 1


CREATE user alter_fun
identified by alter_fun
quota unlimited on users

grant connect, resource to alter_fun

---------------------



ALTER USER alter_fun
IDENTIFIED BY "AlterFun#2026"
ACCOUNT UNLOCK;

GRANT CREATE SESSION, RESOURCE TO alter_fun;

ALTER USER alter_fun
QUOTA UNLIMITED ON users;



---------------------------------

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER TECHSTOREV2 
IDENTIFIED BY TechStore123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO TECHSTOREV2;

GRANT CREATE SESSION TO TECHSTOREV2;
GRANT CREATE TABLE TO TECHSTOREV2;
GRANT CREATE VIEW TO TECHSTOREV2;
GRANT CREATE SEQUENCE TO TECHSTOREV2;
GRANT CREATE PROCEDURE TO TECHSTOREV2;
GRANT CREATE TRIGGER TO TECHSTOREV2;


----------------------------------------------

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER FUNDAMENTOS2_0
IDENTIFIED BY "Fundamentos2#2026"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO FUNDAMENTOS2_0;

GRANT CREATE SESSION TO FUNDAMENTOS2_0;
GRANT CREATE TABLE TO FUNDAMENTOS2_0;
GRANT CREATE VIEW TO FUNDAMENTOS2_0;
GRANT CREATE SEQUENCE TO FUNDAMENTOS2_0;
GRANT CREATE PROCEDURE TO FUNDAMENTOS2_0;
GRANT CREATE TRIGGER TO FUNDAMENTOS2_0;

SELECT username,
       account_status,
       default_tablespace
FROM dba_users
WHERE username = 'FUNDAMENTOS2_0';






---------------------------------------
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;










