-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-07-09 11:14:35 CST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE CATEGORIA 
    ( 
     ID_Categoria     NUMBER (6)  NOT NULL , 
     Nombre_Categoria VARCHAR2 (80 CHAR)  NOT NULL , 
     Descripcion      VARCHAR2 (250 CHAR) , 
     Estado           VARCHAR2 (20 CHAR)  NOT NULL 
    ) 
;

COMMENT ON TABLE CATEGORIA IS 'Representa el catálogo de categorías utilizadas para clasificar los productos tecnológicos de la tienda.'
;

COMMENT ON COLUMN CATEGORIA.ID_Categoria IS 'Identificador único de la categoría' 
;

COMMENT ON COLUMN CATEGORIA.Nombre_Categoria IS 'Nombre de la categoría' 
;

COMMENT ON COLUMN CATEGORIA.Descripcion IS 'Descripción general de la categoría' 
;

COMMENT ON COLUMN CATEGORIA.Estado IS 'Estado de la categoría: Activa o Inactiva' 
;

ALTER TABLE CATEGORIA 
    ADD CONSTRAINT CATEGORIA_PK PRIMARY KEY ( ID_Categoria ) ;

ALTER TABLE CATEGORIA 
    ADD CONSTRAINT CATEGORIA_Nombre_Categoria_UN UNIQUE ( Nombre_Categoria ) ;

CREATE TABLE CLIENTE 
    ( 
     ID_Cliente     NUMBER (8)  NOT NULL , 
     Nombre         VARCHAR2 (80 CHAR)  NOT NULL , 
     Apellidos      VARCHAR2 (120 CHAR)  NOT NULL , 
     Identificacion VARCHAR2 (30 CHAR) , 
     Direccion      VARCHAR2 (250 CHAR)  NOT NULL , 
     Telefono       VARCHAR2 (20 CHAR) , 
     Estado         VARCHAR2 (20 CHAR)  NOT NULL , 
     Correo         VARCHAR2 (120 CHAR) 
    ) 
;

COMMENT ON TABLE CLIENTE IS 'Representa los clientes de la tienda, incluyendo sus datos personales, identificación, dirección y medios de contacto.'
;

COMMENT ON COLUMN CLIENTE.ID_Cliente IS 'Identificador único del cliente' 
;

COMMENT ON COLUMN CLIENTE.Nombre IS 'Nombre del cliente' 
;

COMMENT ON COLUMN CLIENTE.Apellidos IS 'Apellidos del cliente' 
;

COMMENT ON COLUMN CLIENTE.Identificacion IS 'Número de identificación' 
;

COMMENT ON COLUMN CLIENTE.Direccion IS 'Dirección del cliente' 
;

COMMENT ON COLUMN CLIENTE.Telefono IS 'Teléfono de contacto' 
;

COMMENT ON COLUMN CLIENTE.Estado IS 'Estado: Activo o Inactivo' 
;

COMMENT ON COLUMN CLIENTE.Correo IS 'Correo electrónico de contacto del cliente.' 
;

ALTER TABLE CLIENTE 
    ADD CONSTRAINT CLIENTE_PK PRIMARY KEY ( ID_Cliente ) ;

ALTER TABLE CLIENTE 
    ADD CONSTRAINT CLIENTE_Identificacion_UN UNIQUE ( Identificacion ) ;

ALTER TABLE CLIENTE 
    ADD CONSTRAINT CLIENTE_Correo_UN UNIQUE ( Correo ) ;

CREATE TABLE COMPRA 
    ( 
     ID_Compra              NUMBER (10)  NOT NULL , 
     Fecha_Compra           TIMESTAMP WITH LOCAL TIME ZONE  NOT NULL , 
     Numero_Factura         VARCHAR2 (50 CHAR)  NOT NULL , 
     Estado                 VARCHAR2 (20 CHAR)  NOT NULL , 
     PROVEEDOR_ID_Proveedor NUMBER (8)  NOT NULL , 
     LOCAL_ID_Local         NUMBER (8)  NOT NULL 
    ) 
;

COMMENT ON TABLE COMPRA IS 'Representa la cabecera de cada compra realizada por la tienda a un proveedor, incluyendo la fecha, el número de factura y el estado de la transacción.'
;

COMMENT ON COLUMN COMPRA.ID_Compra IS 'Identificador único de la compra' 
;

COMMENT ON COLUMN COMPRA.Fecha_Compra IS 'Fecha y hora de la compra' 
;

COMMENT ON COLUMN COMPRA.Numero_Factura IS 'Número de factura del proveedor' 
;

COMMENT ON COLUMN COMPRA.Estado IS 'Estado: Registrada, Procesada o Anulada' 
;

ALTER TABLE COMPRA 
    ADD CONSTRAINT COMPRA_PK PRIMARY KEY ( ID_Compra ) ;

ALTER TABLE COMPRA 
    ADD CONSTRAINT COMPRA_FACT_PROV_UN UNIQUE ( Numero_Factura , PROVEEDOR_ID_Proveedor ) ;

CREATE TABLE DETALLE_COMPRA 
    ( 
     COMPRA_ID_Compra     NUMBER (10)  NOT NULL , 
     PRODUCTO_ID_Producto NUMBER (8)  NOT NULL , 
     Cantidad             NUMBER (10)  NOT NULL , 
     Costo_Unitario       NUMBER (12,2)  NOT NULL 
    ) 
;

COMMENT ON TABLE DETALLE_COMPRA IS 'Representa los productos, cantidades y costos unitarios incluidos en cada compra realizada por la tienda.'
;

COMMENT ON COLUMN DETALLE_COMPRA.Cantidad IS 'Cantidad comprada' 
;

COMMENT ON COLUMN DETALLE_COMPRA.Costo_Unitario IS 'Costo unitario pagado' 
;

ALTER TABLE DETALLE_COMPRA 
    ADD CONSTRAINT DETALLE_COMPRA_PK PRIMARY KEY ( COMPRA_ID_Compra, PRODUCTO_ID_Producto ) ;

CREATE TABLE DETALLE_VENTA 
    ( 
     VENTA_ID_Venta       NUMBER (10)  NOT NULL , 
     PRODUCTO_ID_Producto NUMBER (8)  NOT NULL , 
     Cantidad             NUMBER (10)  NOT NULL , 
     Precio_Unitario      NUMBER (12,2)  NOT NULL 
    ) 
;

COMMENT ON TABLE DETALLE_VENTA IS 'Representa los productos, cantidades y precios unitarios incluidos en cada venta realizada por la tienda.'
;

COMMENT ON COLUMN DETALLE_VENTA.Cantidad IS 'Cantidad vendida' 
;

COMMENT ON COLUMN DETALLE_VENTA.Precio_Unitario IS 'Precio aplicado al producto' 
;

ALTER TABLE DETALLE_VENTA 
    ADD CONSTRAINT DETALLE_VENTA_PK PRIMARY KEY ( VENTA_ID_Venta, PRODUCTO_ID_Producto ) ;

CREATE TABLE INVENTARIO_LOCAL 
    ( 
     LOCAL_ID_Local       NUMBER (8)  NOT NULL , 
     PRODUCTO_ID_Producto NUMBER (8)  NOT NULL , 
     Stock_Actual         NUMBER (10)  NOT NULL , 
     Stock_Minimo         NUMBER (10)  NOT NULL , 
     Estado               VARCHAR2 (20 CHAR)  NOT NULL 
    ) 
;

COMMENT ON COLUMN INVENTARIO_LOCAL.Stock_Actual IS 'Cantidad actual disponible del producto en el local.' 
;

COMMENT ON COLUMN INVENTARIO_LOCAL.Stock_Minimo IS 'Cantidad mínima recomendada del producto en el local para controlar alertas de bajo inventario.' 
;

COMMENT ON COLUMN INVENTARIO_LOCAL.Estado IS 'Estado del registro de inventario local, utilizado para indicar si se encuentra activo o inactivo.' 
;

ALTER TABLE INVENTARIO_LOCAL 
    ADD CONSTRAINT INVENTARIO_LOCAL_PK PRIMARY KEY ( LOCAL_ID_Local, PRODUCTO_ID_Producto ) ;

CREATE TABLE LOCAL 
    ( 
     ID_Local     NUMBER (8)  NOT NULL , 
     Nombre_Local VARCHAR2 (100 CHAR)  NOT NULL , 
     Direccion    VARCHAR2 (250 CHAR)  NOT NULL , 
     Estado       VARCHAR2 (20 CHAR)  NOT NULL 
    ) 
;

COMMENT ON COLUMN LOCAL.ID_Local IS 'Identificador único del Local' 
;

ALTER TABLE LOCAL 
    ADD CONSTRAINT LOCAL_PK PRIMARY KEY ( ID_Local ) ;

CREATE TABLE PRODUCTO 
    ( 
     ID_Producto            NUMBER (8)  NOT NULL , 
     Nombre_Producto        VARCHAR2 (150 CHAR)  NOT NULL , 
     Descripcion            VARCHAR2 (500 CHAR) , 
     Precio_Venta           NUMBER (12,2)  NOT NULL , 
     Estado                 VARCHAR2 (20 CHAR)  NOT NULL , 
     CATEGORIA_ID_Categoria NUMBER (6)  NOT NULL 
    ) 
;

COMMENT ON TABLE PRODUCTO IS 'Representa cada producto tecnológico disponible para compra y venta, incluyendo su información descriptiva, precio y existencias en inventario.'
;

COMMENT ON COLUMN PRODUCTO.ID_Producto IS 'Identificador único del producto' 
;

COMMENT ON COLUMN PRODUCTO.Nombre_Producto IS 'Nombre comercial del producto' 
;

COMMENT ON COLUMN PRODUCTO.Descripcion IS 'Características o especificaciones del producto' 
;

COMMENT ON COLUMN PRODUCTO.Precio_Venta IS 'Precio unitario de venta del producto' 
;

COMMENT ON COLUMN PRODUCTO.Estado IS 'Estado: Activo, Inactivo o Descontinuado' 
;

ALTER TABLE PRODUCTO 
    ADD CONSTRAINT PRODUCTO_PK PRIMARY KEY ( ID_Producto ) ;

ALTER TABLE PRODUCTO 
    ADD CONSTRAINT PRODUCTO_Nombre_Producto_UN UNIQUE ( Nombre_Producto ) ;

CREATE TABLE PRODUCTO_PROVEEDOR 
    ( 
     PRODUCTO_ID_Producto      NUMBER (8)  NOT NULL , 
     PROVEEDOR_ID_Proveedor    NUMBER (8)  NOT NULL , 
     Codigo_Producto_Proveedor VARCHAR2 (50 CHAR) , 
     Costo_Referencia          NUMBER (12,2) , 
     Estado                    VARCHAR2 (20)  NOT NULL 
    ) 
;

COMMENT ON TABLE PRODUCTO_PROVEEDOR IS 'Representa la relación entre los productos tecnológicos y los proveedores que pueden suministrarlos, incluyendo el código utilizado por el proveedor, el costo de referencia y el estado de la asociación.'
;

COMMENT ON COLUMN PRODUCTO_PROVEEDOR.Codigo_Producto_Proveedor IS 'Código del producto en el catálogo del proveedor' 
;

COMMENT ON COLUMN PRODUCTO_PROVEEDOR.Costo_Referencia IS 'Costo de referencia ofrecido' 
;

COMMENT ON COLUMN PRODUCTO_PROVEEDOR.Estado IS 'Estado de la relación' 
;

ALTER TABLE PRODUCTO_PROVEEDOR 
    ADD CONSTRAINT PRODUCTO_PROVEEDOR_PK PRIMARY KEY ( PROVEEDOR_ID_Proveedor, PRODUCTO_ID_Producto ) ;

CREATE TABLE PROVEEDOR 
    ( 
     ID_Proveedor          NUMBER (8)  NOT NULL , 
     Nombre_Proveedor      VARCHAR2 (150 CHAR)  NOT NULL , 
     Identificacion_Fiscal VARCHAR2 (30 CHAR)  NOT NULL , 
     Direccion             VARCHAR2 (250 CHAR)  NOT NULL , 
     Telefono              VARCHAR2 (20 CHAR)  NOT NULL , 
     Correo                VARCHAR2 (120 CHAR) , 
     Contacto_Principal    VARCHAR2 (120 CHAR)  NOT NULL , 
     Estado                VARCHAR2 (20 CHAR)  NOT NULL 
    ) 
;

COMMENT ON TABLE PROVEEDOR IS 'Representa las empresas o personas proveedoras responsables de suministrar productos tecnológicos a la tienda.'
;

COMMENT ON COLUMN PROVEEDOR.ID_Proveedor IS 'Identificador único del proveedor' 
;

COMMENT ON COLUMN PROVEEDOR.Nombre_Proveedor IS 'Nombre comercial o razón social' 
;

COMMENT ON COLUMN PROVEEDOR.Identificacion_Fiscal IS 'Número de identificación fiscal' 
;

COMMENT ON COLUMN PROVEEDOR.Direccion IS 'Dirección física del proveedor' 
;

COMMENT ON COLUMN PROVEEDOR.Telefono IS 'Número telefónico del proveedor' 
;

COMMENT ON COLUMN PROVEEDOR.Correo IS 'Correo electrónico del proveedor' 
;

COMMENT ON COLUMN PROVEEDOR.Contacto_Principal IS 'Persona principal de contacto' 
;

COMMENT ON COLUMN PROVEEDOR.Estado IS 'Estado: Activo, Inactivo o Suspendido' 
;

ALTER TABLE PROVEEDOR 
    ADD CONSTRAINT PROVEEDOR_PK PRIMARY KEY ( ID_Proveedor ) ;

ALTER TABLE PROVEEDOR 
    ADD CONSTRAINT PROVEEDOR_IDENT_UN UNIQUE ( Identificacion_Fiscal ) ;

ALTER TABLE PROVEEDOR 
    ADD CONSTRAINT PROVEEDOR_Correo_UN UNIQUE ( Correo ) ;

CREATE TABLE VENTA 
    ( 
     CLIENTE_ID_Cliente NUMBER (8)  NOT NULL , 
     ID_Venta           NUMBER (10)  NOT NULL , 
     Fecha_Venta        TIMESTAMP WITH LOCAL TIME ZONE  NOT NULL , 
     Numero_Factura     VARCHAR2 (50 CHAR)  NOT NULL , 
     Estado             VARCHAR2 (20 CHAR)  NOT NULL , 
     LOCAL_ID_Local     NUMBER (8)  NOT NULL 
    ) 
;

COMMENT ON TABLE VENTA IS 'Representa la cabecera de cada venta realizada por la tienda a un cliente, incluyendo la fecha, el número de factura y el estado de la transacción.'
;

COMMENT ON COLUMN VENTA.CLIENTE_ID_Cliente IS 'Cliente asociado con la venta' 
;

COMMENT ON COLUMN VENTA.ID_Venta IS 'Identificador único de la venta' 
;

COMMENT ON COLUMN VENTA.Fecha_Venta IS 'Fecha y hora de la venta' 
;

COMMENT ON COLUMN VENTA.Numero_Factura IS 'Número de factura o comprobante' 
;

COMMENT ON COLUMN VENTA.Estado IS 'Estado: Registrada, Procesada o Anulada' 
;

ALTER TABLE VENTA 
    ADD CONSTRAINT VENTA_PK PRIMARY KEY ( ID_Venta ) ;

ALTER TABLE VENTA 
    ADD CONSTRAINT VENTA_Numero_Factura_UN UNIQUE ( Numero_Factura ) ;

ALTER TABLE COMPRA 
    ADD CONSTRAINT COMPRA_LOCAL_FK FOREIGN KEY 
    ( 
     LOCAL_ID_Local
    ) 
    REFERENCES LOCAL 
    ( 
     ID_Local
    ) 
;

ALTER TABLE COMPRA 
    ADD CONSTRAINT COMPRA_PROVEEDOR_FK FOREIGN KEY 
    ( 
     PROVEEDOR_ID_Proveedor
    ) 
    REFERENCES PROVEEDOR 
    ( 
     ID_Proveedor
    ) 
;

ALTER TABLE DETALLE_COMPRA 
    ADD CONSTRAINT DETALLE_COMPRA_COMPRA_FK FOREIGN KEY 
    ( 
     COMPRA_ID_Compra
    ) 
    REFERENCES COMPRA 
    ( 
     ID_Compra
    ) 
;

ALTER TABLE DETALLE_COMPRA 
    ADD CONSTRAINT DETALLE_COMPRA_PRODUCTO_FK FOREIGN KEY 
    ( 
     PRODUCTO_ID_Producto
    ) 
    REFERENCES PRODUCTO 
    ( 
     ID_Producto
    ) 
;

ALTER TABLE DETALLE_VENTA 
    ADD CONSTRAINT DETALLE_VENTA_PRODUCTO_FK FOREIGN KEY 
    ( 
     PRODUCTO_ID_Producto
    ) 
    REFERENCES PRODUCTO 
    ( 
     ID_Producto
    ) 
;

ALTER TABLE DETALLE_VENTA 
    ADD CONSTRAINT DETALLE_VENTA_VENTA_FK FOREIGN KEY 
    ( 
     VENTA_ID_Venta
    ) 
    REFERENCES VENTA 
    ( 
     ID_Venta
    ) 
;

ALTER TABLE INVENTARIO_LOCAL 
    ADD CONSTRAINT INVENTARIO_LOCAL_LOCAL_FK FOREIGN KEY 
    ( 
     LOCAL_ID_Local
    ) 
    REFERENCES LOCAL 
    ( 
     ID_Local
    ) 
;

ALTER TABLE INVENTARIO_LOCAL 
    ADD CONSTRAINT INVENTARIO_LOCAL_PRODUCTO_FK FOREIGN KEY 
    ( 
     PRODUCTO_ID_Producto
    ) 
    REFERENCES PRODUCTO 
    ( 
     ID_Producto
    ) 
;

ALTER TABLE PRODUCTO_PROVEEDOR 
    ADD CONSTRAINT PROD_PROV_PROVEEDOR_FK FOREIGN KEY 
    ( 
     PROVEEDOR_ID_Proveedor
    ) 
    REFERENCES PROVEEDOR 
    ( 
     ID_Proveedor
    ) 
;

ALTER TABLE PRODUCTO 
    ADD CONSTRAINT PRODUCTO_CATEGORIA_FK FOREIGN KEY 
    ( 
     CATEGORIA_ID_Categoria
    ) 
    REFERENCES CATEGORIA 
    ( 
     ID_Categoria
    ) 
;

ALTER TABLE PRODUCTO_PROVEEDOR 
    ADD CONSTRAINT PRODUCTO_PROVEEDOR_PRODUCTO_FK FOREIGN KEY 
    ( 
     PRODUCTO_ID_Producto
    ) 
    REFERENCES PRODUCTO 
    ( 
     ID_Producto
    ) 
;

ALTER TABLE VENTA 
    ADD CONSTRAINT VENTA_CLIENTE_FK FOREIGN KEY 
    ( 
     CLIENTE_ID_Cliente
    ) 
    REFERENCES CLIENTE 
    ( 
     ID_Cliente
    ) 
;

ALTER TABLE VENTA 
    ADD CONSTRAINT VENTA_LOCAL_FK FOREIGN KEY 
    ( 
     LOCAL_ID_Local
    ) 
    REFERENCES LOCAL 
    ( 
     ID_Local
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             32
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
